version: "3"

volumes:
  postgres-data:
  redis-data:

networks:
  data:
    driver: bridge

services:
  postgres:
    image: "postgres:16"
    container_name: "database"
    restart: always
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "54000:5432"
    networks:
      - data

  redis:
    image: 'redis:7.2.4'
    container_name: 'redis'
    restart: always
    ports:
      - '54001:6379'
    volumes:
      - 'redis-data:/root/redis'
    networks:
      - data