version: "3"


networks:
    data_data:
        external: true
    telemetry_telemetry:
        external: true

services:
  backend:
    image:  ghcr.io/egortarasov/lct-2024/api:amd64-latest
    command: ./main
    volumes:
      - /home/etarasov/lct.yaml:/root/config.yaml
    ports:
      - "9999:9999" # container port defined in config.yaml
    networks:
      - data_data
      - telemetry_telemetry