http-server:
  port: 9999
  domain: api.larek.tech
  cors-origins:
    - https://lct.larek.tech
    - http://localhost:5173

telemetry:
  endpoint: jaeger:4318

postgres:
  user: Dino
  password: Dino-misos2024
  host: pg
  port: 5432
  db: dev
  ssl: false


redis:
  host: redis
  port: 54001
  password: ""
  db: 0

mongo:
  host: mongo
  port: 54002
  user: Dino
  password: Dino-misos2024
  db: production
  collections:
    - events
    - state_property
    - dispatch_services
    - disconnections
    - consumers
    - address_registry
    - mkd
    - property_metering_devices

s3:
  host: s3
  port: 9000
  access_key: # получили из credentials access key из s3 console
  secret_key: # получили из credentials secret key из s3 console
  ssl: false
  buckets:
    - name: uploads
      region: eu-west-1
      lock: true

inference:
  host: ml
  port: 50051