// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "fiber@swagger.io"
        },
        "license": {
            "name": "BSD 3-Clause License",
            "url": "https://raw.githubusercontent.com/EgorTarasov/true-tech/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "auth with email + password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Auth with email creds",
                "parameters": [
                    {
                        "description": "user creds",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.emailCredentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.accessTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "creating email account with FirstName and LastName",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "creating email account",
                "parameters": [
                    {
                        "description": "User Email",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.accessTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errResponse"
                        }
                    }
                }
            }
        },
        "/geo/moek": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geo"
                ],
                "summary": "третья тестовая ручка",
                "parameters": [
                    {
                        "type": "number",
                        "description": "longitude",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "latitude",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "radius",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MoekDTO"
                            }
                        }
                    }
                }
            }
        },
        "/geo/property": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geo"
                ],
                "summary": "вторая тестовая ручка",
                "parameters": [
                    {
                        "type": "number",
                        "description": "longitude",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "latitude",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "radius",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PropertyDTO"
                            }
                        }
                    }
                }
            }
        },
        "/geo/property/id/:object": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geo"
                ],
                "summary": "тестовая ручка на проверку postgis",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PropertyDTO"
                        }
                    }
                }
            }
        },
        "/map/events": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "получение аварийных ситуаций и информации об объекте",
                "parameters": [
                    {
                        "description": "emergencyRequest",
                        "name": "emergencyRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.emergencyRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/search/consumers/filters": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search consumers"
                ],
                "summary": "получение списка всех фильтров для поиска по объектам",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Filter"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/search/consumers/q": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search consumers"
                ],
                "summary": "поиск по объектам consumers с учетом фильтров",
                "parameters": [
                    {
                        "description": "фильтры для поиска",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Filter"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.HeatingPointDTO"
                            }
                        }
                    }
                }
            }
        },
        "/search/objects": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "поиск по объектам (потребителям) тепло энергии",
                "parameters": [
                    {
                        "type": "string",
                        "description": "поисковой запрос",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.StatePropertySearchResult"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.RegisterData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.accessTokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "handler.emailCredentials": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.emergencyRequest": {
            "type": "object",
            "required": [
                "distance",
                "latitude",
                "longitude"
            ],
            "properties": {
                "distance": {
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 0
                },
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                }
            }
        },
        "handler.errResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.DisconnectionDTO": {
            "type": "object",
            "properties": {
                "actualDisconnectionDate": {},
                "actualReconnectionDate": {},
                "disconnectionType": {
                    "type": "string"
                },
                "plannedDisconnectionDate": {},
                "plannedReconnectionDate": {},
                "reason": {
                    "type": "string"
                },
                "registrationDate": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "models.Filter": {
            "type": "object",
            "properties": {
                "filterName": {
                    "type": "string"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.HeatingPointDTO": {
            "type": "object",
            "properties": {
                "balanceHolder": {
                    "type": "string"
                },
                "commissioningDate": {},
                "consumerAddress": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "locationType": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.MoekDTO": {
            "type": "object",
            "properties": {
                "loadActual": {
                    "type": "number"
                },
                "loadAvg": {
                    "type": "number"
                },
                "loadHeating": {
                    "type": "number"
                },
                "loadVent": {
                    "type": "number"
                },
                "number": {
                    "type": "string"
                },
                "point": {},
                "polygon": {},
                "src": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.Point": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.PropertyDTO": {
            "type": "object",
            "properties": {
                "disconnections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DisconnectionDTO"
                    }
                },
                "globalID": {
                    "type": "integer"
                },
                "point": {},
                "polygon": {}
            }
        },
        "models.StatePropertySearchResult": {
            "type": "object",
            "required": [
                "address",
                "municipalDistrict"
            ],
            "properties": {
                "address": {
                    "description": "Полный Адрес в реестре.",
                    "type": "string"
                },
                "area": {},
                "border": {
                    "description": "Граница объекта на карте."
                },
                "center": {
                    "description": "Центр объекта на карте.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Point"
                        }
                    ]
                },
                "class": {
                    "type": "string"
                },
                "feature": {
                    "type": "string"
                },
                "floors": {},
                "municipalDistrict": {
                    "description": "Район округ.",
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "unom": {
                    "description": "Уникальный номер объекта недвижимости.",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.lct.larek.tech",
	BasePath:         "/ //no-lint.",
	Schemes:          []string{},
	Title:            "lct api",
	Description:      "This is a sample swagger for Fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
